apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
  labels:
    application: logging
    component: logstash
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      component: logstash
  template:
    metadata:
      labels:
        application: logging
        component: logstash
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: volume-mount-hack
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/logstash/config"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/conf.d
      containers:
      - name: logstash
        imagePullPolicy: IfNotPresent
        image: 192.168.50.39/library/logstash:6.3.0
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 1
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 514
          name: syslog-tcp
          protocol: TCP
        - containerPort: 514
          name: syslog-udp
          protocol: UDP
        - containerPort: 5044
          name: beats-tcp
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/conf.d
      volumes:
      - name: config
        configMap:
          name: logstash-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: logging
  labels:
    application: logging
    component: logstash
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    component: logstash