filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
  prospectors:
    path: ${path.config}/prospectors.d/*.yml
    reload.enabled: false
filebeat.prospectors:
- enabled: true
  paths:
  - /var/log/*.log
  - /var/log/messages
  - /var/log/syslog
  type: log
- containers.ids:
  - '*'
  processors:
  - add_kubernetes_metadata:
      in_cluster: true
  - drop_event:
      when:
        equals:
          kubernetes.container.name: filebeat
  type: docker
http.enabled: false
http.port: 5066
output.kafka:
  hosts: ['public-cp-kafka-headless.kube-public:9092']
  topic: '%{[fields.log_topic]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
processors:
- add_cloud_metadata: null