# On which specific version of Flink is this based?
# Check https://hub.docker.com/_/flink?tab=tags for current options
FROM flink:1.10.0-scala_2.12

# Install Flink metrics
RUN cp /opt/flink/opt/flink-metrics-prometheus-1.10.0.jar /opt/flink/lib/flink-metrics-prometheus-1.10.0.jar
