kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flink-jars
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
