apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:4.1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
          protocol: TCP
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk-cs:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-svc:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "12"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: kafka
  name: kafka-svc
  namespace: default
spec:
  ports:
  - port: 9092
    targetPort: 9092
  type: NodePort
  selector:
    k8s-app: kafka
