apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-0
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/nfs
    server: 192.168.50.34
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-1
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/nfs
    server: 192.168.50.34
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-2
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/nfs
    server: 192.168.50.34


