apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv0003
spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /data/nfs
      server: 192.168.50.34
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: weblogiclogs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi





---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi






"volumes": [
  {
    "name": "rocksdb",
    "persistentVolumeClaim": {
      "claimName": "hurricane-host-rocksdb"
    }
  }
],
"containers": [
  {
    "name": "hurricane-host",
    "image": "docker.flexem.com/flexem/hurricane.host:v0.2",
    "env": [
      {
        "name": "bootstrap_servers",
        "value": "192.168.50.250:32294"
      },
      {
        "name": "group_id",
        "value": "default11"
      }
    ],
    "resources": {},
    "volumeMounts": [
      {
        "name": "rocksdb",
        "mountPath": "/app/RocksDB"
      }
    ],